apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sources2
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/my-org2
  branch: main
  secretRef:
    name: git-credentials
